# Generated by Django 3.2.7 on 2023-08-12 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'State',
                'verbose_name_plural': 'States',
            },
        ),
        migrations.AddField(
            model_name='people',
            name='state',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='state', to='registry.state', verbose_name='Estado'),
            preserve_default=False,
        ),
    ]
