# Generated by Django 3.2.7 on 2023-08-12 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0003_auto_20230812_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='state',
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postal_code', models.CharField(max_length=9, verbose_name='CEP')),
                ('city', models.CharField(max_length=250, verbose_name='Cidade')),
                ('street', models.CharField(max_length=250, verbose_name='Logradouro')),
                ('number', models.CharField(max_length=10, verbose_name='Número')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='state', to='registry.state', verbose_name='Estado')),
            ],
        ),
    ]
