# Generated by Django 3.2.7 on 2023-08-12 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0004_auto_20230812_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='age',
            field=models.PositiveIntegerField(verbose_name='Idade'),
        ),
    ]
