# Generated by Django 3.2.7 on 2023-08-12 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0005_alter_people_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='person',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='person', to='registry.people'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='people',
            name='address',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='address', to='registry.address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='people',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF'),
        ),
    ]
