# Generated by Django 3.2.7 on 2023-08-12 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0007_remove_people_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='person',
        ),
        migrations.AddField(
            model_name='address',
            name='person_address',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='address', to='registry.people'),
            preserve_default=False,
        ),
    ]
