name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: docker-compose build

      - name: Start services
        run: docker-compose up

      - name: Run makemigrations
        run: docker-compose exec web python manage.py makemigrations

      - name: Run migrate
        run: docker-compose exec web python manage.py migrate

      - name: Shutdown application
        run: docker-compose down
